//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define cmdTS                           23
#define frmSceneryEditor                101
#define frmMain                         102
#define mnuMenu                         103
#define IDC_CURSOR1                     106
#define IDI_ICON1                       107
#define IDI_ICON2                       108
#define IDI_ICON3                       109
#define IDI_ICON4                       110
#define IDI_ICON5                       111
#define IDI_ICON6                       112
#define IDI_ICON7                       115
#define frmDoor                         116
#define frmResize                       118
#define frmInputBox                     119
#define frmRoomStuff                    125
#define frmMiniMap                      126
#define frmHeader                       127
#define frmTE                           128
#define fraTBE                          130
#define fraSS                           131
#define fraStat                         132
#define fraSSE                          133
#define mnuHeaderOpt                    135
#define frmOAM                          136
#define frmClipboard                    138
#define frmECE                          140
#define frmLPE                          141
#define fraBGI                          142
#define frmScrol                        147
#define frmMapData                      149
#define frmExpandAndRepoint             152
#define IDR_MENU1                       155
#define IDD_DIALOG1                     157
#define frmSamusEditor                  157
#define IDR_MENU2                       160
#define picButton                       1001
#define vsbScroll                       1002
#define IDC_COMBO1                      1003
#define cboClip                         1003
#define cboOwner                        1003
#define cboSPal                         1003
#define cboMPal                         1003
#define cboTileset                      1003
#define cbopallettetsa2                 1003
#define cboSlot                         1003
#define cboParts                        1003
#define cboCBNo                         1003
#define cboTextI                        1003
#define cboLayer                        1003
#define cboBGPalette                    1003
#define cboMAreaC                       1004
#define cboMusic                        1004
#define cbopallettetsa                  1004
#define cboRes2                         1004
#define IDC_COMBO6                      1004
#define cmdDraw                         1005
#define cboEffect                       1005
#define cbopallettetsa4                 1005
#define cboRes1                         1005
#define IDC_COMBO7                      1005
#define cboArea                         1006
#define cbopallettetsa3                 1006
#define cboTileset2                     1006
#define IDC_COMBO8                      1006
#define cboRoom                         1007
#define cboMiniX                        1007
#define IDC_COMBO9                      1007
#define picMap                          1008
#define cboMiniY                        1008
#define hsbMap                          1009
#define cboSYP                          1009
#define vsbMap                          1010
#define cmdSave                         1015
#define fraTileset                      1017
#define chkForeground                   1018
#define chkLevel                        1019
#define chkBacklayer                    1020
#define test                            1021
#define chkForeground2                  1021
#define fraClip                         1022
#define lblClip                         1023
#define chkLevel2                       1024
#define chkClip                         1025
#define chkBacklayer2                   1026
#define chkViewF                        1027
#define chkViewL                        1028
#define chkViewB                        1029
#define lblX                            1030
#define lblY                            1031
#define IDC_COMBO2                      1031
#define cboConn                         1031
#define cboSSize                        1031
#define cboSprites                      1031
#define cboBPal                         1031
#define cboTP                           1031
#define IDC_COMBO3                      1032
#define cboDoorType                     1032
#define cboSpriteSet                    1032
#define cboCF                           1032
#define cboFrameIndex                   1032
#define fraDoor                         1033
#define cboCL                           1033
#define chkClip2                        1033
#define lblDoor                         1034
#define cboCB                           1034
#define chkViewBG                       1034
#define cboCBI                          1035
#define cmdSaveDoor                     1043
#define cmdSUP                          1044
#define cmdSDown                        1045
#define cmdSR                           1046
#define cmdSLeft                        1047
#define chkSRe                          1048
#define chkSMove                        1049
#define lblCDoor                        1051
#define ICk                             1052
#define lblDoorType                     1053
#define lblOwnerRoom                    1054
#define lblCDWidth                      1055
#define lblObjT                         1058
#define chkSView                        1059
#define cmdViewConnect                  1072
#define lblC                            1073
#define cboConnect                      1074
#define cboArea1                        1075
#define cboDoor1                        1076
#define cboRoom1                        1077
#define cboArea2                        1078
#define cboDoor2                        1079
#define cboRoom2                        1080
#define cmdSaveConn                     1081
#define lblObjNo                        1082
#define lblResizeTXT                    1084
#define txtWidth                        1085
#define txtHeight                       1086
#define txtLength                       1087
#define txtInput                        1088
#define lblEnter                        1089
#define cmdInputOK                      1090
#define chkST                           1091
#define chkSM                           1092
#define IDC_SCROLLBAR1                  1097
#define hsbSG                           1097
#define hsbC1                           1097
#define IDC_SCROLLBAR2                  1098
#define vsbSG                           1098
#define hsbC2                           1098
#define cmdSSave                        1099
#define cmdSEditForeground              1100
#define hsbC3                           1100
#define cmdSEditBack                    1101
#define cmdSEditBG                      1102
#define cmdraw                          1103
#define fraGrap                         1104
#define fraST                           1105
#define vsbTS                           1106
#define cmdCFore                        1110
#define cmdCLevel                       1111
#define cmdCBack                        1112
#define cmdCClip                        1113
#define cmdROSave                       1114
#define cmdMMSave                       1115
#define framt                           1116
#define fraMinimap                      1117
#define txtFO                           1123
#define txtLO                           1128
#define cmdSaveH                        1129
#define txtBO                           1133
#define txtBIO                          1138
#define cmdChangeS                      1139
#define cboTrans                        1141
#define cboSG                           1142
#define cboEC                           1143
#define txtSOffset                      1144
#define lblNumber                       1145
#define lstOffsets                      1146
#define txtString                       1147
#define fraPic                          1148
#define cmdSaveText                     1149
#define chkHorz                         1151
#define chkVert                         1152
#define cmdSaveBlock                    1153
#define vertchk2                        1154
#define chkHor2                         1155
#define vertchk                         1156
#define chkHor                          1157
#define vertchk4                        1158
#define chkHor4                         1159
#define vertchk3                        1160
#define chkHor3                         1161
#define fraTTileset                     1162
#define chkScroll                       1165
#define cmdSSOk                         1166
#define chkResizeDoors                  1166
#define cmdSSCancel                     1167
#define fraSpriteSS                     1168
#define cmdNext                         1169
#define cmdPrev                         1170
#define lblSpriteblah                   1171
#define chkVC                           1172
#define lstNumbers                      1173
#define txtshp                          1174
#define txtlhp                          1175
#define txtm                            1176
#define txtpb                           1177
#define txtsm                           1178
#define txtHealth                       1179
#define txtDMG                          1180
#define txtu1                           1181
#define cmdSavestats                    1182
#define chkDoors                        1183
#define txtud                           1183
#define txtu2                           1184
#define chkSprites                      1184
#define txtu3                           1185
#define cmdES                           1185
#define lbltst                          1186
#define lstSprites                      1187
#define fraTiles                        1189
#define fraPal                          1190
#define lstPopulation                   1191
#define IDC_BUTTON1                     1192
#define lblPaletteInfo                  1193
#define buttonDeleteDoor                1193
#define btnDeleteScroll                 1193
#define IDC_BUTTON3                     1193
#define lblSpriteInfo                   1194
#define cmdSaveSet                      1195
#define IDC_BUTTON5                     1195
#define cmdDumpPal                      1196
#define IDC_BUTTON6                     1196
#define cmdSaveToFree                   1196
#define cmdInsertPal                    1197
#define cmdDeleteFrame                  1197
#define cmdSaveGraphics                 1198
#define btnLoadGFX2                     1198
#define cmdInsertPal2                   1199
#define IDC_BUTTON8                     1199
#define cmdSavePal                      1200
#define IDC_BUTTON9                     1200
#define lblBlah                         1201
#define cboControl1                     1202
#define cboControl2                     1203
#define IDC_LIST1                       1203
#define cboControl3                     1204
#define fraSprPreview                   1204
#define cboControl4                     1205
#define txtFOff                         1205
#define cmdGTO                          1206
#define fraParts                        1207
#define fraFrame                        1208
#define txtFPOff                        1209
#define txtTimer                        1210
#define cmdSFD                          1211
#define cmdSPD                          1212
#define txtTimer2                       1212
#define fraSprPreview2                  1213
#define cmdDeletePart                   1213
#define cboShape                        1214
#define cboSize                         1215
#define cmdErase                        1215
#define lblForeground                   1216
#define fraSprPreview3                  1216
#define fraSprAnimPreview               1216
#define lblLevel                        1217
#define txtGFX1                         1217
#define lblBackLayer                    1218
#define txtGFX2                         1218
#define lblClipdata                     1219
#define txtFPOff3                       1219
#define fraInfo                         1220
#define txtFPOff4                       1220
#define IDC_BUTTON2                     1221
#define chkDTrans                       1222
#define chkDTrans2                      1223
#define txtSV                           1224
#define cmdSetSprite                    1225
#define txtDWidth                       1227
#define txtDHeight                      1228
#define chkBit1                         1229
#define chkBit2                         1230
#define chkBit4                         1231
#define chkBit8                         1232
#define chkBit10                        1233
#define chkBit20                        1234
#define chkBit40                        1235
#define chkBit80                        1236
#define cmdClearScene                   1237
#define rdo0                            1238
#define rdo1                            1239
#define rdo2                            1240
#define cmdSelFile                      1241
#define lblFileName                     1242
#define cmdBGi                          1243
#define cmdLPE                          1244
#define lblC1                           1245
#define lblC2                           1246
#define lblC3                           1247
#define cmdANC                          1248
#define cmdSaveColors                   1249
#define chkHS                           1250
#define cboDScroll                      1251
#define cmdBG                           1252
#define cbArea                          1252
#define lblHeaderOffset                 1253
#define cmdBG2                          1253
#define btnAddDoor                      1254
#define cmdBG3                          1254
#define cboDScroll2                     1255
#define grpBoxObj                       1256
#define IDC_EDIT1                       1257
#define txtByte1                        1257
#define IDC_EDIT2                       1258
#define txtByte2                        1258
#define IDC_EDIT3                       1259
#define txtByte3                        1259
#define IDC_EDIT4                       1260
#define txtByte4                        1260
#define IDC_EDIT5                       1261
#define txtLong                         1261
#define frmScroll                       1262
#define btnAddScroll                    1263
#define frmMain1                        1263
#define lblSpriteObjectCount            1264
#define fraMain                         1264
#define lblCurDoorCount                 1265
#define frmMainExperiment               1265
#define lblCurLabelCount                1266
#define lblOldCompressed                1267
#define lblCurrentSize                  1268
#define btnAddObject                    1269
#define btnDeleteObj                    1270
#define btnAddPartZ                     1274
#define btnNewFrame                     1275
#define btnCopyFrame                    1276
#define lblTileNumber                   1277
#define btnCopyPart                     1278
#define btnLoadGFX1                     1279
#define cboX                            1283
#define IDC_COMBO5                      1284
#define cboY                            1284
#define lblOAM1                         1285
#define lblOAM2                         1286
#define lblOAM0                         1287
#define cboPriority                     1288
#define btnTest                         1289
#define btnCHeader                      1290
#define cboFrameTableCombo              1291
#define IdSprPrev                       1292
#define IDC_COMBO4                      1293
#define cboOAMSelection                 1293
#define grpMap                          1294
#define IDC_TAB1                        1295
#define tabMain                         1295
#define IDC_CHECK2                      1297
#define IDC_CHECK3                      1298
#define IDC_CHECK4                      1299
#define IDC_CHECK5                      1300
#define IDC_CHECK6                      1301
#define IDC_CHECK7                      1302
#define IDC_CHECK8                      1303
#define IDC_CHECK9                      1304
#define IDC_CHECK10                     1305
#define cboPoseitem                     1306
#define chkAnimates                     1307
#define IDC_CHECK11                     1314
#define IDC_CHECK12                     1315
#define IDC_CHECK13                     1316
#define IDC_CHECK14                     1317
#define IDC_CHECK15                     1318
#define IDC_CHECK16                     1319
#define IDC_CHECK17                     1320
#define IDC_CHECK18                     1321
#define DoorID                          9000
#define mnuOpen                         40001
#define mnuRR                           40003
#define mnuRS                           40004
#define mnuTE                           40005
#define mnuHeader                       40006
#define mnuMini                         40007
#define mnuTSA                          40008
#define mnuSE                           40010
#define MNUBAH                          40012
#define mnuRH                           40013
#define mnuRTH                          40014
#define mnuRAH                          40015
#define mnuRAH2                         40016
#define mnuBAH2                         40017
#define mnuBCH                          40018
#define mnuSSE                          40019
#define mnuEG                           40020
#define mnuIG                           40021
#define mnuEP                           40022
#define mnuIP                           40023
#define mnuSOE                          40024
#define mnuClipboard                    40025
#define mnuSP                           40026
#define cmdSG                           40027
#define mnuIR                           40028
#define mnuER                           40029
#define mnuEB                           40031
#define mnuIPSP                         40032
#define mnuInsert                       40033
#define ID_GENERALTOOLS_DUMPASAREA      40034
#define ID_DAS                          40035
#define ID_DAA                          40036
#define ID_GENERALTOOLS_SWITCHGUI       40037
#define ID_GENERALTOOLS_SAMUSEDITOR     40038
#define ID_ROOMTOOLS_ZOOM               40039
#define ID_ZOOM_NORMAL                  40040
#define ID_ZOOM_1                       40041
#define ID_ZOOM_2                       40042
#define ID_IMPORT_CUSTOMBACKGROUND      40043
#define ID_IMPORT_OAM                   40044
#define ID_IMPORT_TILESET               40045
#define ID_BACKGROUND_RAWFILE           40046
#define ID_BACKGROUND_IMAGE             40047
#define ID_CUSTOMBACKGROUND_RAWFILE     40048
#define ID_CUSTOMBACKGROUND_IMAGE       40049
#define ID_OAM_RAWIMAGE                 40050
#define ID_OAM_IMAGE                    40051
#define ID_TILESET_RAWIMAGE             40052
#define ID_TILESET_IMAGE                40053
#define ID_SPECIFICINPUT_IMPORTPAL      40054
#define ID_SPECIFICINPUT_IMPORTTILES    40055
#define ID_SPECIFICINPUT_IMPORTTILEMAP  40056
#define ID_BACKGROUND_256X256           40057
#define ID_BACKGROUND_512X256           40058
#define ID_BACKGROUND_256X512           40059
#define ID_MAP_VIEWFOREGROUND           40060
#define ID_MAP_VIEWLEVELLAYER           40061
#define ID_MAP_VIEWBACKLAYER            40062
#define ID_MAP_VIEWBACKGROUND           40063
#define ID_MAP_SHOWSPRITES              40064
#define ID_MAP_SHOWSCROLLS              40065
#define ID_MAP_SHOWCLIPDATA             40066
#define ID_ROOMTOOLS_EDITLEVELPAL       40067
#define ID_MAP_SHOWTRANSPARENCY         40068
#define ID_MAP_ANIMATE                  40069
#define ID_FRAMEOPTIONS_NEWFRAME        40070
#define ID_FRAMEOPTIONS_COPYFRAME       40071
#define ID_FRAMEOPTIONS_SAVEFRAME       40072
#define ID_FRAMEOPTIONS_DELETEFRAME     40073
#define ID_FRAMEOPTIONS_RELOADFROMOFFSET 40074
#define ID_PARTOPTIONS_COPYPART         40075
#define ID_PARTOPTIONS_ADDPART          40076
#define ID_PARTOPTIONS_DELETEPART       40077

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         40078
#define _APS_NEXT_CONTROL_VALUE         1309
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
